AWSTemplateFormatVersion: "2010-09-09"

Resources:
  MyRole:
    Type: AWS::IAM::Role
    DeletionPolicy: Retain
    Properties: 
      AssumeRolePolicyDocument: >-
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Service": "lambda.amazonaws.com"
              },
              "Action": "sts:AssumeRole"
            }
          ]
        }
      Description: Allows Lambda functions to call AWS services on your behalf.
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/service-role/AWSLambdaENIManagementAccess
        # missing data from what is in AWS to check drift detection
        # - arn:aws:iam::aws:policy/service-role/AmazonS3ObjectLambdaExecutionRolePolicy

      # NOTE: not including these properties yet
      # MaxSessionDuration: Integer
      # Path: String
      # PermissionsBoundary: String
      # Policies: 
      #   - Policy

      RoleName: my-lambda-role
      Tags: 
        - Key: Team
          Value: d2a
